# Install apache using ansible 

---
- name: Install Apache and configure timezone
  hosts: all
  become: true

  tasks:
    - name: Update package cache and install Apache
      yum:
        name: httpd
        state: present

    - name: Set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create a simple HTML page
      copy:
        content: "<html><body><h1>Hello from {{ inventory_hostname }}</h1></body></html>"
        dest: /var/www/html/index.html

